name: Build and Push a Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1 (Build the docker image)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose build

  # Job 2 (Test the Image by running it)
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Test the Image by running it
        run: docker compose up -d

  # Job 3 (Build and push the docker images to dockerhub)
  push_to_registry:
    name: Push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the image to the registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mo-books:latest